version: '2.2'
volumes:
  dbbackups:
  postgis-data:

services:
  db:
    image: kartoza/postgis:14-3.3
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lets_play
    ports:
      - '127.0.0.1:5432:5432'
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=postgres pg_isready -h 127.0.0.1 -U postgres -d lets_play"

#  dbbackups:
#    image: kartoza/pg-backup:14-3.3
#    hostname: pg-backups
#    volumes:
#      - dbbackups:/backups
#    environment:
#      - DUMPPREFIX=PG_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASS=postgres
#      - POSTGRES_PORT=5432
#      - POSTGRES_HOST=db
#    restart: on-failure
#    depends_on:
#      db:
#        condition: service_healthy
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lets-play:latest
    ports:
      - "8082:8080"
    environment:
      - DB_SERVER=db
    depends_on:
      db:
        condition: service_healthy
