spring:
  application:
    name: "let's play" 
  datasource:
#    Т.к. у меня windows - я юзаю VM для докера, а у него свой IP.
#    Пусть тут полежит, если ты не против
    url: jdbc:postgresql://192.168.99.102:5432/lets_play
#    url: jdbc:postgresql://localhost:5432/lets_play
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yaml
server:
  port: 8082
